CPPFLAGS += -Wno-unused-variable -Wno-deprecated-declarations -Wno-cpp -Wno-write-strings
CPPFLAGS += -DDEBUG
ARDUINO_LIBS = DallasTemperature OneWire
BOARD_TAG = pro5v328

include ../arduino_inc.mk

